services:
  
  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    image: employeehub-frontend
    container_name: employeehub-frontend
    ports:
      - "80"
    depends_on:
      - api
    networks:
      - employeehub-network

  api:
    build:
      context: ../backend
      dockerfile: EmployeeHub.Api/Dockerfile
    image: employeehub-api
    container_name: employeehub-api
    ports:
      - "5132"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=EmployeeHub;
        User Id=sa;
        Password=${SA_PASSWORD};
        TrustServerCertificate=True;
      Authentication__Authority: http://keycloak:8080/auth/realms/employeehub
      Authentication__MetadataAddress: http://keycloak:8080/auth/realms/employeehub/.well-known/openid-configuration
      Ollama__Endpoint: http://ollama:11434/api/chat
      Ollama__Model: llama3.2

    depends_on:
      sqlserver:
        condition: service_healthy
      keycloak:
        condition: service_started
      ollama:
        condition: service_started

    volumes:
      - ./api-logs:/app/logs

    networks:
      - employeehub-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: employeehub-sqlserver

    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1", "-C"]
      interval: 15s
      timeout: 10s
      retries: 12
      start_period: 30s

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    
    networks:
      - employeehub-network

  postgres:
    image: postgres:17
    container_name: employeehub-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /Volumes/Development/Database/Postgres2:/var/lib/postgresql/data
    networks:
      - employeehub-network
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: employeehub-keycloak
    command: ["start-dev", "--import-realm"]

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY_HEADERS: xforwarded

    ports:
      - "8080:8080"

    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json

    depends_on:
      - postgres

    networks:
      - employeehub-network
  
  ollama:
    image: ollama/ollama:latest
    container_name: employeehub-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - employeehub-network
    environment:
      - OLLAMA_KEEP_ALIVE=-1

  nginx:
    image: nginx:alpine
    container_name: employeehub-nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - frontend
      - api
      - keycloak

    networks:
      - employeehub-network

volumes:
  sqlserver-data:
  postgres-data:
  ollama-data:

networks:
  employeehub-network:
    driver: bridge